1006/ws03_3/day14_exercise3/eithers/urls.py
from django.urls import path

from . import views

app_name = 'eithers'

urlpatterns = [
    path('', views.index, name='index'),
    path('eithers/create/', views.create, name="create"),
    path('eithers/<int:pk>/', views.detail, name="detail"), 
    path('eithers/random/', views.random, name="random"),
    path('eithers/<int:pk>/comment', views.comment_create, name="comment_create"),   
]

1006/ws03_3/day14_exercise3/eithers/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    title = models.CharField(max_length=200)
    RED_TEAM = models.CharField(max_length = 100)
    BLUE_TEAM = models.CharField(max_length = 100)

    def __str__(self):
        return self.title


class Comment(models.Model):
    TEAM_PICK = (
        ('RED TEAM','RED TEAM'),
        ('BLUE TEAM','BLUE TEAM'),
    )
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    pick = models.CharField(max_length=10, choices = TEAM_PICK, default='RED TEAM')
    content = models.CharField(max_length=100)

    def __str__(self):
        return self.title

1006/ws03_3/day14_exercise3/eithers/forms.py
from django import forms
from .models import Question, Comment

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = '__all__'


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('question',)

1006/ws03_3/day14_exercise3/eithers/views.py
from django.shortcuts import render, redirect

from .models import Question, Comment
from .forms import QuestionForm, CommentForm
from random import choice
# Create your views here.

def index(request):
    questions = Question.objects.order_by('pk')
    context = {
        'questions': questions,
    }
    return render(request, 'eithers/index.html', context)


def detail(request, pk):
    question = Question.objects.get(pk=pk)
    comment_form = CommentForm()
    comments = question.comment_set.all()
    context = {
        'question': question,
        'comment_form':comment_form,
        'comments':comments,
    }
    return render(request, 'eithers/detail.html', context)



def create(request):
    if request.method == "POST":
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save()
            return redirect('eithers:detail', question.pk)
    else:
        form = QuestionForm()
    context = {
        'form':form,
    }
    return render(request, 'eithers/create.html', context)


def comment_create(request, pk):
    question = Question.objects.get(pk=pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.question = question
        comment.save()
    return redirect('eithers:detail', question.pk)


def random(request):
    question = choice(Question.objects.all())
    comment_form = CommentForm()
    comments = question.comment_set.all()
    context = {
        'question': question,
        'comment_form':comment_form,
        'comments':comments,
    }
    return render(request, 'eithers/detail.html', context)

1006/ws03_3/day14_exercise3/eithers/templates/eithers/create.html
{% extends 'base.html' %}

{% block contents %}
  <h1>CREATE</h1>
  <hr>
  <a href="{% url 'eithers:index' %}">BACK</a>
  <form action="{% url 'eithers:create' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create">
  </form>

{% endblock contents %}

1006/ws03_3/day14_exercise3/eithers/templates/eithers/detail.html
{% extends 'base.html' %}

{% block contents %}
  <h1>DETAIL</h1>
  <hr>
  <h1>{{ question.title }}</h1>
  <h3>Red TEAM</h3>
  <h4>=> {{ question.RED_TEAM }}</h4>
  <br>
  <br>
  <h3>Blue TEAM</h3>
  <h4>=> {{ question.BLUE_TEAM }}</h4>
  <hr>
  <a href="{% url 'eithers:index' %}">BACK</a>
  <hr>
  <h3>댓글 작성</h3>
  <form action="{% url 'eithers:comment_create' question.pk %}" method="POST">
    {% csrf_token %}
    {{ comment_form.as_p }}
    <input type="submit" value="작성">
  </form>
  <hr>
  <ul>
    {% for comment in comments %}
      <li> {{ comment.pick }} - {{ comment.content }} </li>
    {% endfor %}
  </ul>
{% endblock contents %}

1006/ws03_3/day14_exercise3/eithers/templates/eithers/index.html
{% extends 'base.html' %}

{% block contents %}
  <h1>INDEX</h1>
  <hr>
  {% for question in questions %}
    <p> {{ question.pk }}번 이슈</p>
    <h2> {{ question.title }}</h2>
    <a href="{% url 'eithers:detail' question.pk %}">DETAIL</a>
    <hr>
  {% endfor %}

{% endblock contents %}